// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSbheXrPK8gGzr0XRgLwC_uSxmZB_YpSM',
    appId: '1:1025991026053:web:629aea4e9f1fb5af5690ec',
    messagingSenderId: '1025991026053',
    projectId: 'sos-app-1b56d',
    authDomain: 'sos-app-1b56d.firebaseapp.com',
    storageBucket: 'sos-app-1b56d.firebasestorage.app',
    measurementId: 'G-1TH6Y1EXYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAelU-HtQWQL6rGbnBanvVfGh7FiIE2bMg',
    appId: '1:1025991026053:android:90793326256b0a815690ec',
    messagingSenderId: '1025991026053',
    projectId: 'sos-app-1b56d',
    storageBucket: 'sos-app-1b56d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSlFQWpZ8KY-NtOrx7Hiw4mWZ9Ov1MD2E',
    appId: '1:1025991026053:ios:a25b09aa1ce3cd4b5690ec',
    messagingSenderId: '1025991026053',
    projectId: 'sos-app-1b56d',
    storageBucket: 'sos-app-1b56d.firebasestorage.app',
    iosBundleId: 'com.example.sosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSlFQWpZ8KY-NtOrx7Hiw4mWZ9Ov1MD2E',
    appId: '1:1025991026053:ios:a25b09aa1ce3cd4b5690ec',
    messagingSenderId: '1025991026053',
    projectId: 'sos-app-1b56d',
    storageBucket: 'sos-app-1b56d.firebasestorage.app',
    iosBundleId: 'com.example.sosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSbheXrPK8gGzr0XRgLwC_uSxmZB_YpSM',
    appId: '1:1025991026053:web:68ffc8ce7b1eea6c5690ec',
    messagingSenderId: '1025991026053',
    projectId: 'sos-app-1b56d',
    authDomain: 'sos-app-1b56d.firebaseapp.com',
    storageBucket: 'sos-app-1b56d.firebasestorage.app',
    measurementId: 'G-3YEL2X1459',
  );
}
